services:
  flower-garden-app:
    image: node:24-alpine
    working_dir: /app
    env_file: .env
    volumes:
      - ./:/app/
    command: sh -c "cd /app && npm run dev"
    ports:
      - ${APP_PORT}:80
    user: "1800:1800"
    tmpfs:
      - /tmp:exec,nosuid,nodev
      - /app/${DIR_CACHE_PATH}/:rw,uid=1800,gid=1800
