services:
  flower-garden-app:
    image: florobart/flower-garden-app:latest
    restart: always
    working_dir: /app
    env_file:
      - ./.env
    networks:
      - flower-garden-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "${APP_PORT:-}:80"
    read_only: true
    user: "1800:1800"
    tmpfs:
      - /tmp:exec,nosuid,nodev
      - /app/${DIR_CACHE_PATH}/:rw,uid=1800,gid=1800
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://flower-garden-app:80/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  flower-garden-net:
    external: true
